# install/helm/custom-values.yaml
# Forced dynamic UIDs for OpenShift Restricted PSA
initResources:
  limits: { cpu: 200m, memory: 256Mi }
  requests: { cpu: 100m, memory: 128Mi }

deployment:
  replicaCount: 1
  resources:
    limits: { cpu: 500m, memory: 1Gi }
    requests: { cpu: 250m, memory: 512Mi }

  securityContext:
    enabled: true
    # Set these to null to allow OpenShift to auto-assign the allowed range
    runAsUser: null
    runAsGroup: null
    fsGroup: null
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: RuntimeDefault

image:
  repository: ghcr.io/opennsw/oga-backend
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

setup:
  securityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: RuntimeDefault
configuration:
  database:
    type: "postgres"
    config:
      host: "nsw-db"
      name: "configdb"
      username: "postgres" 
    runtime:
      host: "nsw-db"
      name: "runtimedb"
      username: "postgres"

auth:
  existingSecret: "thunder-auth-secret"
  secretKey: "adminPassword"