apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-register-namespaces"
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-register-namespaces"
      labels:
        {{- include "temporal.labels" . | nindent 8 }}
    spec:
      {{- if (index .Values "temporal" "global" "imagePullSecrets") }}
      imagePullSecrets:
        {{- toYaml (index .Values "temporal" "global" "imagePullSecrets") | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
      - name: register
        image: "{{ (index .Values "temporal" "server" "image" "repository") }}:{{ (index .Values "temporal" "server" "image" "tag") }}"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        command:
          - /bin/sh
          - -c
          - |
            echo "Waiting for Temporal Frontend to respond..."
            until temporal operator --address {{ .Release.Name }}-frontend:7233 cluster describe; do sleep 2; done;
            {{- range .Values.nsw.namespaces | default (list "default") }}
            echo "Registering namespace {{ . }}..."
            temporal operator --address {{ $.Release.Name }}-frontend:7233 namespace create --namespace {{ . }} || echo "Namespace already exists."
            {{- end }}
