# OGA-FCAU Portal Values
# Usage: helm upgrade --install oga-fcau-app ./deployments/helm/oga-app -f deployments/helm/oga-app/fcau-app-values.yaml --history-max 3

nameOverride: oga-fcau-app
fullnameOverride: oga-fcau-app

config:
  instanceConfig: "fcau"
  apiBaseUrl: "https://oga-fcau-backend-national-single-window-platform.apps.sovecloud.akaza.lk/api"
  idpBaseUrl: "https://idp-thunder-national-single-window-platform.apps.sovecloud.akaza.lk"
  idpClientId: "OGA_PORTAL_APP_FCAU"
  appUrl: "https://oga-fcau-app-national-single-window-platform.apps.sovecloud.akaza.lk"

route:
  host: oga-fcau-app-national-single-window-platform.apps.sovecloud.akaza.lk
