# temporal values for auto-setup
global:
  namespace: "national-single-window-platform"
  clusterDomain: "apps.sovecloud1.akaza.lk"

image:
  repository: ghcr.io/opennsw/temporal-auto-setup
  tag: "1.28.3"
  pullPolicy: IfNotPresent

ui:
  image:
    repository: ghcr.io/opennsw/temporal-ui
    tag: "2.48.0"
    pullPolicy: IfNotPresent
  route:
    name: "temporal-ui"
    host: ""

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 7233

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  host: "nsw-db"
  credentialsSecretName: "nsw-db-credentials"

# Temporal environment configuration
env:
  dbName: "temporal_db"
  extraEnv: []

temporalNamespaces:
  - national-single-window-platform
