# Staging Overrides for temporal
temporal:
  server:
    config:
      persistence:
        datastores:
          default:
            sql:
              databaseName: temporal_db_staging
          visibility:
            sql:
              databaseName: temporal_visibility_db_staging
