# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  goimports:
    local-prefixes: github.com/OpenNSW/nsw

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  exclude-dirs:
    - mocks
    - vendor
  max-same-issues: 0
  max-issues-per-linter: 0

run:
  timeout: 5m
  modules-download-mode: readonly
