apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  labels:
    {{- include "nsw-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | default "postgres" | quote }}
  user: {{ .Values.auth.username | default "postgres" | quote }}
  password: {{ .Values.auth.password | default "postgres" | quote }}
