apiVersion: v1
kind: Secret
metadata:
  name: nsw-db-credentials
  labels:
    {{- include "nsw-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | default "postgres" | quote }}
  user: {{ .Values.auth.username | default "postgres" | quote }}
  password: {{ required "A database password is required (.Values.auth.password)" .Values.auth.password | quote }}