# Dev Overrides for oga-backend
global:
  clusterDomain: "apps.sovecloud1.akaza.lk"
  namespace: "national-single-window-platform"

replicaCount: 1

config:
  database:
    host: "nsw-db"
    credentialsSecretName: "nsw-db-credentials"
  # Internal URL for communication between pods
  nswApiBaseUrl: "http://dev-nsw-api/api/v1"
  allowedOrigins: "https://dev-oga-fcau-national-single-window-platform.apps.sovecloud1.akaza.lk,https://dev-oga-ird-national-single-window-platform.apps.sovecloud1.akaza.lk,https://dev-oga-npqs-national-single-window-platform.apps.sovecloud1.akaza.lk"

route:
  host: ""
  enabled: true
