apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oga-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oga-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oga-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oga-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: VITE_INSTANCE_CONFIG
              value: {{ .Values.config.instanceConfig | quote }}
            - name: VITE_API_BASE_URL
              value: {{ .Values.config.apiBaseUrl | quote }}
            - name: VITE_IDP_BASE_URL
              value: {{ .Values.config.idpBaseUrl | quote }}
            - name: VITE_IDP_CLIENT_ID
              value: {{ .Values.config.idpClientId | quote }}
            - name: VITE_APP_URL
              value: {{ .Values.config.appUrl | quote }}
            - name: VITE_IDP_SCOPES
              value: {{ .Values.config.idpScopes | quote }}
            - name: VITE_IDP_PLATFORM
              value: {{ .Values.config.idpPlatform | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
