apiVersion: v1
kind: Service
metadata:
  name: {{ include "oga-multi-frontend.fullname" . }}
  labels:
    {{- include "oga-multi-frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range $key, $agency := .Values.agencies }}
    {{- if $agency.enabled }}
    - name: {{ $key }}
      port: {{ if eq $key "fcau" }}80{{ else if eq $key "ird" }}81{{ else }}82{{ end }}
      targetPort: {{ $key }}-http
      protocol: TCP
    {{- end }}
    {{- end }}
  selector:
    {{- include "oga-multi-frontend.selectorLabels" . | nindent 4 }}
