apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nsw-api.fullname" . }}-services
  labels:
    app.kubernetes.io/name: {{ include "nsw-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  services.json: |-
    {
      "version": "1.0",
      "services": {{ .Values.services | toJson }}
    }
