{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "nsw-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nsw-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  host: {{ .Values.route.host | quote }}
  to:
    kind: Service
    name: {{ include "nsw-api.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" | quote }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" | quote }}
  {{- end }}
{{- end }}