apiVersion: v1
kind: Service
metadata:
  name: {{ include "thunder.fullname" . }}
  labels:
    {{- include "thunder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: 8081        # Internal Cluster port
      targetPort: 8081  # Matches OGA Application port
      protocol: TCP
      name: http     
  selector:
    {{- include "thunder.selectorLabels" . | nindent 4 }}